spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: ${url}
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}
  profiles:
    active: db

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml